Inspired by Malcom Gladwell's book Outliers.
Random sample of 10000 trying to determine the improtance of luck in success.

In [38]:
import numpy as np
from matplotlib import pyplot as plt

In [39]:
population = np.arange(0, 20000, 1)
skill = np.random.randint(101, size=20000)
intellect = np.random.randint(101, size=20000)
grit = np.random.randint(101, size=20000)
luck = np.random.randint(101, size=20000)

Skill, intellect and grit will account 90% of success, luck will account for 10%.

Calculate combined skill, intellect and grit

In [55]:
combined_sik = skill + intellect + grit
print(combined_sik)
print(max(combined_sik))

[151 187 158 ... 170 194 133]
293


In [56]:
def find_max_values(x):
    return np.argsort(x)[-10:]

In [57]:
max_10_sik = find_max_values(combined_sik)
print(max_10_sik)

[12991  9700  2024  6551 19377  3775 10999  7457  2298  2243]


In [58]:
for i in max_10_sik:
    print(combined_sik[i])
    

286
286
288
289
289
289
290
291
291
293


^ 10 highest combined skill, intellect and grit values.

now combine skill, intellect, grit values with luck(score out of 300):

In [59]:
skill_intel_know_luck = 0.9*combined_sik + 0.1*luck


Now find arguments of max skill, intelligence, knowledge and luck combined:

In [60]:
max_10_sikl = find_max_values(skill_intel_know_luck)
print(max_10_sikl)
for i in max_10_sikl:
    print(skill_intel_know_luck[i])

[12986  2298  7096 19377  7457  6551  1524  2024 10999  2243]
263.1
263.90000000000003
264.1
264.5
264.70000000000005
264.8
265.7
268.7
269.2
273.7


In [61]:
matching = 0

for i in max_10_sik:
    for j in max_10_sikl:
        if i == j:
            matching += 1
print(matching)

7


Therefore, 7 random characters who were in the top 10 for skill, intellect and knowlede also appeared in the list when luck was factored in.
